#!/bin/bash

if [ $# != 1 ]
then
	echo "参数错误"
	echo "usage: ./write filename"
	exit 0
fi

if [ ! -f $1 ]
then
	echo "文件不存在"
	exit 0
fi

if [ ! -e /dev/ttyACM0 ]
then
	echo "错误: 未检测到编程器/dev/ttyACM0"
	exit 0
fi

echo -e "\033[33m探测flash...\033[0m"
sudo flashrom -p serprog:dev=/dev/ttyACM0:4000000,spispeed=36000000 | tee /tmp/flashrom.log

if [ $? != 0 ]
then
	echo -e "\033[31m错误: 未知异常，可尝试重新插拔编程器\033[0m"
	exit 1
fi

flash=`grep "No EEPROM/flash device found" /tmp/flashrom.log`

if [ -n "$flash" ]
then
	echo -e "\033[31m错误: 未检测到flash，可尝试重新放置flash\033[0m"
	exit 2
fi

flash=`grep "flash chip" /tmp/flashrom.log | awk -F' ' '{print $5,$6,$7,$8}'`
echo -e "\033[32m型号: $flash\033[32m"

echo -e "\033[33m烧录flash...\033[0m"
sudo flashrom -p serprog:dev=/dev/ttyACM0:4000000,spispeed=36000000 -w $1 2>/tmp/flashrom_error.log

if [ $? != 0 ]
then
	cat /tmp/flashrom_error.log
	match=`grep "doesn't match the flash chip's size" /tmp/flashrom_error.log`
	if [ -n "$match" ]
	then
		flashsize=`cat /tmp/flashrom_error.log | awk -F'(' '{printf $3}' | awk -F' ' '{printf $1}'`
		filesize=`cat /tmp/flashrom_error.log | awk -F'(' '{printf $2}' | awk -F' ' '{printf $1}'`

		if [ $filesize -ge $flashsize ]
		then
			echo -e "\033[31m错误: 文件大于flash容量\033[0m"
			exit 1
		fi

		echo -e "\033[33m文件大小与flash容量不匹配，进行自动处理...\033[0m"
		echo -e "\033[33m  读取flash...\033[0m"
		sudo flashrom -p serprog:dev=/dev/ttyACM0:4000000,spispeed=36000000 -r /tmp/readx.bin
		echo -e "\033[33m  读取完成，进行文件合并...\033[0m"
		dd if=/tmp/readx.bin of=/tmp/remfill.bin ibs=$filesize skip=1
		cat $1 /tmp/remfill.bin > /tmp/tempx.bin
		temp=`printf "%08x" $((filesize-1))`
		echo -e "\033[33m  生成flash layout...\033[0m"
		echo "00000000:$temp flashzone" > /tmp/flashrom.layout
		echo -e "\033[33m处理完成，开始烧录...\033[0m"
		sudo flashrom -p serprog:dev=/dev/ttyACM0:4000000,spispeed=36000000 -l /tmp/flashrom.layout -i flashzone -w /tmp/tempx.bin

		if [ $? != 0 ]
		then
			echo -e "\033[31m错误: 未知异常，需要手动处理\033[0m"
			exit 1
		fi

		echo -e "\033[32m烧录完成\033[0m"
		sudo rm -rf /tmp/*.bin /tmp/flashrom*
	else
		echo -e "\033[31m错误: 不支持的异常类型，需要手动处理\033[0m"
	fi
else
	echo -e "\033[32m烧录完成\033[0m"
fi
